
software_dest: /opt/software
sources: "{{software_dest}}/sources"
builds:  "{{software_dest}}/builds"

streaming_data_types_src: https://github.com/ess-dmsc/streaming-data-types.git
streaming_data_types_version: master
streaming_data_types: "{{software_dest}}/streaming-data-types-{{streaming_data_types_version}}"

generator_src: https://github.com/ess-dmsc/sinq-amorsim
generator_home: "{{amor_dir}}/simfiles"
generator_branch: master

generator_inc: '"{{streaming_data_types}}"'

scl: "scl enable devtoolset-6 --"

conan_profile: 'gcc63'
