- name: Make sure that simfiles directory exists
  file: 
    path: "{{simfiles_dir}}"
    state: directory 
    recurse: yes
  become: yes

- name: be sure EL734 controller is installed
  become: yes
  copy:
    src: el734controller.py
    dest: "{{simfiles_dir}}"
    mode: 0755

- name: be sure EL734 motor and parameters are installed
  become: yes
  copy:
    src: "{{item}}"
    dest: "{{simfiles_dir}}"
  with_items: 
    - el734motor.py
    - mota
    - motb
    - motc

- name: be sure motor simulation services are installed
  become: yes
  copy:
    src: "{{item}}"
    dest: /usr/lib/systemd/system
  with_items:
    - mota.service
    - motb.service
    - motc.service

- name: be sure motor simulation services are enabled
  become: yes
  service:
    name: "{{item}}"
    enabled: yes
    state: stopped
  with_items:
    - mota
    - motb
    - motc
    
- name: Make sure that epics dir exists
  file: 
    path: "{{epics_dir}}"
    state: directory 
    recurse: yes
  become: yes

- name: be sure motor substitutions files are installed
  become: yes
  copy:
    src: "{{item}}"
    dest: "{{epics_dir}}"
  with_items:
    - mota.substitutions
    - motb.substitutions
    - motc.substitutions
