- name: Make sure that /opt/amor/epics exists
  file: path=/opt/amor/epics state=directory recurse=yes

- name: make sure that the IOC executable is installed
  become: yes
  copy:
    src: sinqEPICS
    dest: /opt/amor/epics
    mode: 0755

- name: make sure that envPaths installed
  become: yes
  copy:
    src: envPaths
    dest: /opt/amor/epics

- name: make sure that dbd files are installed
  become: yes
  copy:
    src: dbd
    dest: /opt/amor/epics
 

- name: make sure that the st.cmd file is installed
  become: yes
  copy:
    src: st.cmd
    dest: /opt/amor/epics
    mode: 0755
