- name: Make sure that some packages are not available
  become: yes
  package:
    name: python-twisted-core
    state: absent

- name: be sure required packages are installed
  become: yes
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - epel-release
    - python
    - python-devel
    - python-setuptools
    - python-pip
    - python2-crypto
    - python-zope-interface
    - pyOpenSSL
    - openssl-devel
    - automake
    - autoconf

- name: install python packages
  become : yes
  pip:
    name: "{{item}}"
    state: latest
  with_items:
    - pip
    - pyepics
    - twisted
    - service_identity

- name: Make sure that pip installation doesn't interfere
  become: yes
  pip:
    name: pyopenssl
    state: absent

- name: figure out if procServ exists
  stat: 
    path: /usr/local/bin/procServ
  register: procServ

- name: install procServ but only when it does not exist
  block:
    - git:
        repo: 'https://github.com/ralphlange/procServ.git'
        dest: /tmp/procServ
        version: V2.6.0
    - shell: autoconf
      args:
        chdir: /tmp/procServ
      ignore_errors: yes
    - shell: make && ./configure --disable-doc
      args:
        chdir: /tmp/procServ
    - make: 
       chdir: /tmp/procServ
       target: install
      become: true
    - file:
        path: /tmp/procServ
        state: absent
  when: not procServ.stat.exists 

- name: Amorsim source dir
  file: 
    path: "{{amorsim_dir}}" 
    state: directory  
    owner: "{{ansible_user_uid}}" 
    group: "{{ansible_user_gid}}"
  become: true

- name: Amorsim source
  synchronize:
    src:  "{{role_path}}/../../../."
    dest: "{{amorsim_dir}}"

- name: find out if /nfs exists
  stat:
    path: /nfs
  register: nfs

- name: If nfs does not exists, make a link to /opt
  block:
    - file:
        src: /opt
        dest: /nfs
        state: link
      become: true
  when: not nfs.stat.exists