- name: be sure required packages are installed
  become: yes
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - epel-release
    - python
    - python-devel
    - python-pip
    - python2-crypto
    - openssl-devel

- name: install python packages
  become : yes
  pip:
    name: "{{item}}"
    state: latest
  with_items:
    - pip
    - pyepics
    - twisted
    - pyopenssl
    - service_identity 

- name: download procServ
  git:
    repo: 'https://github.com/ralphlange/procServ.git'
    dest: /tmp/procServ
    version: V2.6.0

- name: configure procServ
  shell: make && ./configure --disable-doc
  args:
    chdir: /tmp/procServ

- name: build and install procServ
  become: yes
  make: 
    chdir: /tmp/procServ
    target: install

- name: be sure procServ directory is absent
  file:
    path: /tmp/procServ
    state: absent

- name: Amorsim source dir
  file: 
    path: "{{amorsim_dir}}" 
    state: directory  
    owner: "{{ansible_user_uid}}" 
    group: "{{ansible_user_gid}}"
  become: true

- name: Amorsim source
  synchronize:
    src:  "{{role_path}}/../../../."
    dest: "{{amorsim_dir}}"
