---
- name: Install deps via yum
  yum: name={{ item }}
  with_items:
    - python
    - python-devel
    - python-pip
    - readline
    - readline-devel
  tags:
    - dornier
  become: true

- name: Install deps via pip
  pip: name={{ item }}
  environment:
    EPICS_BASE: "{{ lookup('env','EPICS_BASE') }}"
    EPICS_HOST_ARCH: "{{ lookup('env','EPICS_HOST_ARCH') }}"
  with_items:
    - pyepics
    - pcaspy
  tags:
    - dornier
  become: true

# Variables for install location are currently defined on top level

- name: Push europeanspallationsource/essiip-fakesinqhw
  git:
    repo: "{{src_repo_essiip_fakesinqhw}}"
    dest: "{{install_path}}/essiip-fakesinqhw"
  tags:
    - dornier
  become: true

# copy and synchronize modules work only from local to remote, therefore use command:
- name: Copy service for Dornier chopper
  command: cp {{install_path}}/essiip-fakesinqhw/fakeDChopper/chopper_SIM_SINQ.service  /usr/lib/systemd/system/
  tags:
    - dornier
  become: yes
