---
#- include_vars: chopper_dornier_host.yml

# The chopper facade is already in the sinq repository

- file:
    path: "{{chopper_ess_facade_for_sinq_conf_path}}"
    state: directory

- name: ESS facade for Dornier chopper (configuration file)
  template:
    src: chopper-ess-facade-for-sinq.conf.j2
    dest: "{{chopper_ess_facade_for_sinq_conf_path}}/chopper-ess-facade-for-sinq.conf"
    mode: u=rw,g=rw,o=r
  #notify: restart redis

- name: Copy service for ESS facade for Dornier chopper (facade-chopper-dornier)
  template:
    src: facade-chopper-dornier.service.j2
    dest: /usr/lib/systemd/system/facade-chopper-dornier.service
    mode: u=rw,g=rw,o=r
