- name: check if kafka is already installed
  stat:
    path: "{{ install_dir }}/kafka-server.sh"
  register: kafka_installed 
    
- name: check if kafka package is available locally
  stat:
    path: "{{ local_download_dir }}/{{ kafka_pkg }}.tar.gz"
  when: not kafka_installed.stat.exists
  register: kafka_pkg_local 
    
- name: be sure kafka directory exists
  file:
    dest: "{{ kafka_install_dir }}"
    state: directory
  become: yes
