---
- name: Install OpenJDK
  become_method: sudo
  yum:
    name: java-1.8.0-openjdk-headless.x86_64
    state: latest

- name : Download and unpack Kafka
  unarchive:
    src: "{{kafka_src}}"
    dest: "{{kafka_install_dir}}"
    copy: no

- name: Kafka Configuration file
  template:
    src: server.properties.j2
    dest: "{{kafka_config_dir}}/server.properties"
    mode: a=r,u=rw
