---
- name: Install OpenJDK
  become: yes
  become_method: sudo
  yum: name=java-1.8.0-openjdk-headless.x86_64 state=present

- name : Unpack Kafka
  become: yes
  become_method: sudo
  unarchive: src="{{ kafka_src }}" dest="{{ kafka_install_dir }}" copy=no

- name: Install kafka executables and libs using stow
  become: yes
  become_method: sudo
  command: "stow -t {{ install_dir }} {{ kafka_pkg }} chdir={{ stow_dir }}"
