---
  - name: Install kafka
    include: install-kafka.yml
    when: "{{ is_kafka_server }} == true"

  - name: Runk kafka and zookeper as services
    include: kafka-service.yml

  - name: Run kafka
    include: run-kafka.yml
