---

- name: check for kafka installation
  include: check-kafka.yml
  
- name: Install kafka
  include: install-kafka.yml
  when: not kafka_installed.stat.exists
  become: yes
  
- name: Run kafka service
  include: run-kafka.yml
  become: yes
