---
- stat: path="{{ kafka_home }}"
  register: kafka_dir

- name: Install kafka
  include: install-kafka.yml
  environment:
    KAFKA_HOME: "{{ kafka_home }}"
  when: not kafka_dir.stat.exists

- name: Run kafka
  include: run-kafka.yml
  
