---
- stat: path="{{ kafka_home }}"
  register: kafka_dir

- name: Install kafka
  include: install-kafka.yml
  environment:
    KAFKA_HOME: "{{ kafka_home }}"
  when: ("{{ is_kafka_server }} == true") and not kafka_dir.stat.exists

- name: Runk kafka and zookeper as services
  include: kafka-service.yml

- name: Run kafka
  include: run-kafka.yml
  
