---
- name: copy service files
  become: yes
  copy:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system
    force: yes
  with_items:
    - kafka.service
    - zookeeper.service

- name: start kafka
  become: yes
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - zookeeper
    - kafka
