generator_src: https://mib_mic@bitbucket.org/europeanspallationsource/sinq-amorsim.git
generator_home: /opt/amor/simfiles

rdkafka_src: https://github.com/edenhill/librdkafka.git
rdkafka_home: /usr/local

