---
- name: Download flatbuffers
  git:
    repo: "{{ flatbuffers_src }}"
    dest: "{{ flatbuffers_src_dir }}"

- name: Create build folder
  file:
    path: "{{ flatbuffers_src_dir }}/build"
    state: directory

- name: Compile flatbuffers
  shell: "cmake -DCMAKE_INSTALL_PREFIX={{ flatbuffers_install_dir }} ../ && make chdir={{ flatbuffers_src_dir }}/build"

- name: Install flatbuffers
  become: yes
  shell: "make install chdir={{ flatbuffers_src_dir }}/build"

- name: Create link in {{ install_dir }}
  become: yes
  shell: "stow -t {{ install_dir }} flatbuffers chdir={{ stow_dir }}"
