---

- name: Download flatbuffers
  git:
    repo: "{{flatbuffers_src}}"
    dest: "{{sources}}/flatbuffers-{{flatbuffers_version}}"
    version: "{{flatbuffers_version}}"

- name: Create build folder
  file:
    path: "{{builds}}/flatbuffers-{{flatbuffers_version}}"
    state: directory

- name: Configure flatbuffers
  command: "cmake -DCMAKE_INSTALL_PREFIX={{flatbuffers}} {{sources}}/flatbuffers-{{flatbuffers_version}}"
  args:
    chdir: "{{builds}}/flatbuffers-{{flatbuffers_version}}"

- name: Compile and install flatbuffers
  make:
    target: install
    chdir: "{{builds}}/flatbuffers-{{flatbuffers_version}}"
    params:
      NUM_THREADS: 4

