---

- name: Download flatbuffers
  git:
    repo: "{{flatbuffers_src}}"
    dest: "{{sources}}/flatbuffers-{{flatbuffers_version}}"
    version: "{{flatbuffers_version}}"

- debug:
     msg: "NeXus status: {{sources}}/flatbuffers-{{flatbuffers_version}}"

- name: Create build folder
  file:
    path: "{{builds}}/flatbuffers-{{flatbuffers_version}}"
    state: directory

- name: Configure flatbuffers
  command: "{{scl}} cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX={{flatbuffers}} {{sources}}/flatbuffers-{{flatbuffers_version}}"
  args:
    chdir: "{{builds}}/flatbuffers-{{flatbuffers_version}}"

- name: Compile and install flatbuffers
  make:
    target: install
    chdir: "{{builds}}/flatbuffers-{{flatbuffers_version}}"
    params:
      NUM_THREADS: 4

- name: Test for flatc
  stat: 
    path: "{{flatbuffers}}/bin/flatc"
  register: flatc

- name: Install flatc manually when above failed to do this
  file:
    path: "{{flatbuffers}}/bin"
    state: directory
  when: not flatc.stat.exists

- name: Copy the files 
  copy:
    src:  "{{builds}}/flatbuffers-{{flatbuffers_version}}/flatc"
    dest: "{{flatbuffers}}/bin/flatc"
    mode: 0755
  when: not flatc.stat.exists
