---
- name: Clone flatbuffers
  git: repo=https://github.com/google/flatbuffers.git dest=/tmp/flatbuffers

- name: Create build folder
  file: path=/tmp/flatbuffers/build state=directory

- name: Compile flatbuffers
  shell: cmake ../ && make chdir=/tmp/flatbuffers/build

- name: Install flatbuffers
  become: yes
  become_method: sudo
  shell: make install chdir=/tmp/flatbuffers/build

- name: Export environment
  shell: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
