---
- name: make sure repositories are installed
  yum:
    name: '{{item}}'
  with_items:
    - centos-release-scl
    - epel-release
  become: yes

- name: enable repositories
  command: yum-config-manager --enable rhel-server-rhscl-7-rpms epel
  become: yes

- name: make sure requirements are installed
  yum:
    name: '{{item}}'
  with_items:
    - cmake
    - devtoolset-6
  become: yes

- name: create folder {{software_dest}}
  become: yes
  file:
    path: '{{software_dest}}'
    state: directory

- name: checks for files
  include: check.yml

- name: install flatbuffers
  include: flatbuffers.yml
  when:
    st_flatbuffers.stat.exists == False
  become: yes

- name: install rdkafka
  include: rdkafka.yml
  when:
    st_rdkafka.stat.exists == False
  become: yes

- name: install rapidjson
  include: rapidjson.yml
  when:
    st_rapidjson.stat.exists == False
  become: yes

- name: checkout streaming-data-types
  include: streaming_data_types.yml
  when:
    st_sdt.stat.exists == False
  become: yes

- name: checkout googletest
  include: googletest.yml
  become: yes

- name: install neventGenerator
  include: nevent_generator.yml 

- name: make sure generator service file is installed
  become: yes
  template: 
    src: generator.j2 
    dest: /usr/lib/systemd/system/generator.service
