---
- name: install required python modules
  include: python_modules.yml
  become: yes
  become_method: sudo

- name: install 0MQ
  include: zmq.yml
  when: use_zmq

- name: checks for files
  include: check.yml

- name: install NeXus
  include: nexus.yml
  when:
    not lib_nexus.stat.exists
    
- name: install neventGenerator
  include: nevent_generator.yml 

- name: make sure generator service file is installed
  become: yes
  template: 
    src: generator.j2 
    dest: /usr/lib/systemd/system/generator.service
