---
- name: Make sure cmake is installed
  include: cmake.yml 

- name: Make sure stow is installed
  include: stow.yml
  
- name: 0MQ library
  include: zmq.yml
  when: use_zmq

- name: checks for files
  include: check.yml

- name: NeXus library
  include: nexus.yml
  when:
    not lib_nexus.stat.exists
    
- name: rdkafka library
  include: rdkafka.yml
  when:
    not lib_rdkafka.stat.exists

- name: flatbuffers library
  include: flatbuffers.yml 
  when:
    not lib_flatbuffers.stat.exists
  
- name: neventGenerator
  include: nevent_generator.yml 

- name: add extra_path to ld_library_path
  become: yes
  become_method: sudo
  lineinfile: dest=/etc/environment line='export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib64'
    
- name: be sure generator service file is installed
  become: yes
  copy:
    src: generator.service
    dest: /usr/lib/systemd/system
