---
# prerequisites
- name: Make sure yum repositories are installed
  yum:
    name: '{{item}}'
  with_items:
    - centos-release-scl
    - epel-release
  become: yes

- name: Enable repositories
  command: yum-config-manager --enable rhel-server-rhscl-7-rpms epel
  become: yes

- name: Make sure requirements are installed
  yum:
    name: '{{item}}'
  with_items:
    - cmake
    - devtoolset-6
  become: yes

# folder
- name: Create destination folder {{software_dest}}
  become: yes
  file:
    path: '{{software_dest}}'
    state: directory

# streaming-data-types
- name: Make sure streaming-data-types is present
  stat: 
    path: "{{streaming_data_types}}"
  register: check_streaming_data_types

- name: Download schema repository
  git:
    repo: "{{streaming_data_types_src}}"
    dest: "{{streaming_data_types}}"
  env:
    streaming_data_types_dir: "{{streaming_data_types}}"
  when:
    check_streaming_data_types.stat.exists == False
  become: yes

# install AMORgenerator
- name: Install neventGenerator
  include: nevent_generator.yml 

# install service files
- name: Make sure generator service file is installed
  become: yes
  template: 
    src: generator.j2 
    dest: /usr/lib/systemd/system/generator.service
