---
- name: make sure cmake is installed
  yum:
    name: cmake
  become: yes

- name: install required python modules
  include: python_modules.yml
  become: yes

- name: install 0MQ
  include: zmq.yml
  when: use_zmq

- name: create software storage folder
  become: yes
  file:
    path: "{{software_dest}}"
    state: directory

- name: checks for files
  include: check.yml

- name: install NeXus
  include: nexus.yml
  when:
    st_nexus.stat.exists == False
  become: yes

- name: install flatbuffers
  include: flatbuffers.yml
  when:
    st_flatbuffers.stat.exists == False
  become: yes

- name: install rdkafka
  include: rdkafka.yml
  when:
    st_rdkafka.stat.exists == False
  become: yes

- name: install rapidjson
  include: rapidjson.yml
  when:
    st_rapidjson.stat.exists == False
  become: yes

- name: install streaming-data-types
  include: streaming_data_types.yml
  when:
    st_sdt.stat.exists == False
  become: yes

- name: install neventGenerator
  include: nevent_generator.yml 
  become: yes

- name: make sure generator service file is installed
  become: yes
  template: 
    src: generator.j2 
    dest: /usr/lib/systemd/system/generator.service
