---
- name: Cmake
  include: cmake.yml 

- name: NeXus library
  include: nexus.yml 

- name: 0MQ library
  include: zmq.yml
  
- name: flatbuffers library
  include: flatbuffers.yml 

- name: neventGenerator
  include: nevent_generator.yml 

