- stat: path="{{ generator_home }}"
  register: generator_dir

- name: Create generator_home folder
  become: yes
  become_method: sudo
  file: path="{{ generator_home }}" state=directory
  when: not generator_dir.stat.exists

- name: Clone generator from repository
  git: repo="{{ generator_src }}" dest=/tmp/neventGenerator force=yes accept_hostkey=yes

- name: Create build folder
  file: path=/tmp/neventGenerator/neventGenerator/build state=directory
  
- name: Configure installation
  shell: cmake -DCMAKE_INSTALL_PREFIX="{{ generator_home }}" ../ chdir=/tmp/neventGenerator/neventGenerator/build 

- name: Compile
  shell: make chdir=/tmp/neventGenerator/neventGenerator/build chdir=/tmp/neventGenerator/neventGenerator/build 

- name: Install
  shell: make install chdir=/tmp/neventGenerator/neventGenerator/build
  become: yes
  become_method: sudo

    
- name: Make generator executable
  become: yes
  become_method: sudo
  file: path="{{ generator_home }}/AMORgenerator" mode="a+x"
  
- name: be sure detector simulation service file installed
  become: yes
  copy:
    src: generator.service
    dest: /usr/lib/systemd/system
