---

- name: Create folder '{{generator_home}}'
  file: 
    path: "{{generator_home}}" 
    state: directory
  become: yes

- name: Clone branch '{{generator_branch}}' from '{{generator_src}}' 
  git: 
    repo: "{{generator_src}}" 
    dest: /tmp/sinq-amorsim 
    force: yes 
    accept_hostkey: yes 
    version: "{{generator_branch}}"

- name: Remove old build folder
  file: 
    path: /tmp/sinq-amorsim/neventGenerator/build
    state: absent

- name: Create build folder
  file: 
    path: /tmp/sinq-amorsim/neventGenerator/build 
    state: directory

- name: Manage dependencies with Conan
  include: conan.yml

- name: Configure installation
  command: '{{scl}} cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX={{generator_home}} -DCMAKE_INCLUDE_PATH={{generator_inc}} ../ '
  args:
    chdir: /tmp/sinq-amorsim/neventGenerator/build
 
- name: Install dependencies using conan
  include: conan.yml

- name: Install
  make: 
    target: install 
    chdir: /tmp/sinq-amorsim/neventGenerator/build
    params:
      NUM_THREADS: 4
  become: yes

- name: Delete sources and build
  file:
    path: /tmp/sinq-amorsim
    state: absent

- name: Make generator executable
  file: 
    path: "{{generator_home}}/AMORgenerator" 
    mode: "a+x"
  become: yes

- name: be sure EL737 counterbox is installed
  copy:
    src: "{{item}}"
    dest: "{{simfiles_dir}}"
  with_items:
    - el737counter.py
    - generator.py
    - config.json
  become: yes
