---

- name: Create generator_home folder
  file: 
    path: "{{generator_home}}" 
    state: directory
  become: yes

- name: Clone generator from repository
  git: 
    repo: "{{generator_src}}" 
    dest: /tmp/sinq-amorsim 
    force: yes 
    accept_hostkey: yes 
    version: "{{generator_version}}"

- name: Remove any old build folder
  file: 
    path: /tmp/sinq-amorsim/neventGenerator/build
    state: absent

- name: Create build folder
  file: 
    path: /tmp/sinq-amorsim/neventGenerator/build 
    state: directory

- name: Configure installation
  command: '{{scl}} cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX={{generator_home}} -DCMAKE_INCLUDE_PATH={{generator_inc}} -DCMAKE_LIBRARY_PATH={{generator_lib}} -DCMAKE_PROGRAM_PATH={{flatbuffers}}/bin ../ '
  args:
    chdir: /tmp/sinq-amorsim/neventGenerator/build
  environment:
    PATH: '{{flatbuffers}}/bin:{{ ansible_env.PATH }}'
 
- name: Install
  make: 
    target: install 
    chdir: /tmp/sinq-amorsim/neventGenerator/build
    params:
      NUM_THREADS: 4
  become: yes

- name: delete sources and build
  file:
    path: /tmp/sinq-amorsim
    state: absent

- name: Make generator executable
  file: 
    path: "{{generator_home}}/AMORgenerator" 
    mode: "a+x"
  become: yes

- name: be sure EL737 counterbox is installed
  copy:
    src: "{{item}}"
    dest: "{{simfiles_dir}}"
  with_items:
    - el737counter.py
    - generator.py
    - config.json
  become: yes
