---
- name: Install HDF5
  yum: 
    name: hdf5-devel
    state: latest

- name: Download NeXus repository
  git:
    repo: "{{nexus_src}}"
    dest: "{{sources}}/nexusformat-{{nexus_version}}"
    version: "{{nexus_version}}"

- name: Create build folder
  file:
    path: "{{builds}}/nexusformat-{{nexus_version}}"
    state: directory

- name: Configure NeXus
  command: "cmake -DENABLE_HDF5=1 -DENABLE_CXX=1 -DENABLE_APPS=ON -DCMAKE_INSTALL_PREFIX={{nexus}} {{sources}}/nexusformat-{{nexus_version}}"
  args:
    chdir: "{{builds}}/nexusformat-{{nexus_version}}"

- name: Compile and install NeXus
  make:
    target: install
    chdir: "{{builds}}/nexusformat-{{nexus_version}}"
    params:
      NUM_THREADS: 4
