---
- name: Download rapidjson
  git:
    repo: "{{rapidjson_src}}"
    dest: "{{sources}}/rapidjson-{{rapidjson_version}}"
    force: yes
    
- name: Create build folder
  file:
    path: "{{builds}}/rapidjson-{{rapidjson_version}}"
    state: directory

- name: Configure rapidjson
  command: "cmake -DCMAKE_INSTALL_PREFIX={{rapidjson}} {{sources}}/rapidjson-{{rapidjson_version}}"
  args:
    chdir: "{{builds}}/rapidjson-{{rapidjson_version}}"

- name: Compile and install rapidjson
  make:
    target: install
    chdir: "{{builds}}/rapidjson-{{rapidjson_version}}"
    params:
      NUM_THREADS: 4
