---
- name: Download librdkafka
  git:
    repo: "{{ rdkafka_src }}"
    dest: "{{ rdkafka_src_dir }}"
    force: yes
    
- name: Configure, compile and install rdkafka
  shell: "./configure --prefix=/opt/stow/librdkafka && make clean && make chdir={{ rdkafka_src_dir }}"

- name: Install rdkafka
  become: yes
  shell: "make install chdir={{ rdkafka_src_dir }}"

- name: Create link in {{ install_dir }}
  become: yes
  shell: "stow -t {{ install_dir }} librdkafka chdir={{ stow_dir }}"
