---

- name: Download librdkafka
  git:
    repo: "{{rdkafka_src}}"
    dest: "{{sources}}/rdkafka-{{rdkafka_version}}"
    force: yes
    
- name: Configure rdkafka
  command: "{{scl}} ./configure --prefix={{rdkafka}}"
  args:
    chdir: "{{sources}}/rdkafka-{{rdkafka_version}}"

- name: Compile rdkafka
  make:
    chdir: "{{sources}}/rdkafka-{{rdkafka_version}}"
    params:
      NUM_THREADS: 4

- name: Install rdkafka
  make:
    target: install
    chdir: "{{sources}}/rdkafka-{{rdkafka_version}}"
    params:
      NUM_THREADS: 4

