kafka_src: http://www-eu.apache.org/dist/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz
kafka_version: "0.10.0.0"
kafka_home: /opt/kafka

gradle_version: "2.14"
gradle_url: https://services.gradle.org/distributions/


