- hosts: simulation
  roles:
    - playbook_local_deps
    - common
    - motors
    - magnet 
    - sps
    - dimetix
    - epics
    - generator
    - chopper_dornier
    - forward-epics-to-kafka
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"
    # Used in roles: playbook_local_deps, forward-epics-to-kafka:
    repo_loc_essiip_fakesinqhw: ../../essiip-fakesinqhw
    repo_loc_forward_epics_to_kafka: ../../forward-epics-to-kafka

- hosts: kafka_server
  tags:
    - kafkaServer
  roles:
    - role: kafka
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"

- hosts: generator_host
  tags:
    - generator
  roles:
    - generator
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"
