- hosts: simulations
  roles:
    - common
    - motors
    - epics

- hosts: kafka
  tags:
    - kafkaServer
  vars:
    use_kafka: true
  roles:
    - { role: kafka, is_kafka_server: false , wants_rdkafka: true, when: "{{ use_kafka }} == true" }


- hosts: kafka
  tags:
    - neventGenerator
  roles:
    - generator
