- hosts: simulation
  roles:
    - common
    - motors
    - magnet 
    - sps
    - dimetix
    - epics

- hosts: kafka_server
  tags:
    - kafkaServer
  roles:
#    - role: kafka
    - role: generator

- hosts: generator_host
  tags:
    - neventGenerator
  roles:
    - generator
