- hosts: simulations
  roles:
    - common
    - motors
    - epics

- hosts: localhost
  tags:
    - kafka
  vars:
    use_kafka: true
  roles:
    - { role: kafka, is_kafka_server: false , wants_rdkafka: true, when: "{{ use_kafka }} == true" }
