- hosts: simulation
  roles:
    - common
    - motors
    - magnet 
    - sps
    - dimetix
    - epics
    - generator
    - chopper_dornier
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"

- hosts: kafka_server
  tags:
    - kafkaServer
  roles:
    - role: kafka
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"

- hosts: generator_host
  tags:
    - generator
  roles:
    - generator
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"
