- hosts: 127.0.0.1
  connection: local
  tasks:
  - assert:
      that: ansible_version.major >= 2 and ansible_version.minor >= 2

- hosts: simulation
  roles:
    - common
    - motors
    - magnet 
    - sps
    - dimetix
    - epics
    - generator
    - chopper_dornier
    - forward-epics-to-kafka
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"
    # Used in roles: playbook_local_deps, forward-epics-to-kafka:
    repo_loc_essiip_fakesinqhw: "{{playbook_dir}}/../../essiip-fakesinqhw"
    repo_loc_forward_epics_to_kafka: "{{playbook_dir}}/../../forward-epics-to-kafka"

- hosts: kafka_server
  tags:
    - kafkaServer
  roles:
    - role: kafka
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"

- hosts: generator_host
  tags:
    - generator
  roles:
    - generator
  vars:
    local_download_dir: "/tmp"
    stow_dir: "/opt/stow"
    install_dir: "/usr/local"
