- hosts: simulation
  roles:
    - common
    - motors
    - magnet 
    - sps
    - dimetix
    - epics

- hosts: kafka_server
  tags:
    - kafkaServer
  vars:
    is_kafka_server: true
  roles:
    - { role: kafka, when: "{{ is_kafka_server }} == true" }


- hosts: generator_host
  tags:
    - neventGenerator
  roles:
    - generator
