
- hosts: 127.0.0.1
  connection: local
  tasks:
  - assert:
      that: ansible_version.major >= 2 and ansible_version.minor >= 2

- hosts: simulation
  tags:
    - simulation
  roles:
    - common
    - playbook_local_deps
    - motors
    - magnet 
    - sps
    - dimetix
    - epics
    - chopper_dornier
    - generator
  vars:
    # Used in roles: playbook_local_deps, forward-epics-to-kafka:
    repo_loc_essiip_fakesinqhw: "{{playbook_dir}}/../../essiip-fakesinqhw"
  environment:
    path_include_epics_pvAccess: "{{ lookup('env', 'EPICS_MODULES_PATH') }}/pvAccessCPP/5.0.0/3.15.4/include"
    path_include_epics_pvData: "{{ lookup('env', 'EPICS_MODULES_PATH') }}/pvDataCPP/5.0.2/3.15.4/include"
    path_include_epics_pvDatabase: "{{ lookup('env', 'EPICS_MODULES_PATH') }}/pvDatabaseCPP/4.2.0/3.15.4/include"
