- hosts: 127.0.0.1
  connection: local
  tasks:
  - assert:
      that: ansible_version.major >= 2 and ansible_version.minor >= 2

- hosts: simulation
  tags:
    - simulation
  roles:
    - common
    - playbook_local_deps
    - motors
    - magnet 
    - sps
    - dimetix
    - epics
    - generator
    - chopper_dornier
    - forward-epics-to-kafka
    - generator
  vars:
    # Used in roles: playbook_local_deps, forward-epics-to-kafka:
    repo_loc_essiip_fakesinqhw: "{{playbook_dir}}/../../essiip-fakesinqhw"
    repo_loc_forward_epics_to_kafka: "{{playbook_dir}}/../../forward-epics-to-kafka"
    use_zmq: false
