- hosts: simulation
  roles:
    - common
    - motors
    - magnet 
    - sps
    - dimetix
    - epics
    - generator
    - chopper_dornier
    
- hosts: kafka_server
  tags:
    - kafkaServer
  roles:
    - role: kafka

- hosts: generator_host
  tags:
    - generator
  roles:
    - generator
