- name: Refresh systemd
  shell: systemctl daemon-reload
  become: yes

- name: change motor mota simulation state
  become: yes
  service:
    name: mota
    state: "{{ new_state }}"

- name: change motor motb simulation state
  become: yes
  service:
    name: motb
    state: "{{ new_state }}"

- name: change motor motc simulation state
  become: yes
  service:
    name: motc
    state: "{{ new_state }}"

- name: change AMOR magnet simulation state
  become: yes
  service:
    name: amormagnet
    state: "{{ new_state }}"

- name: change AMOR SPS simulation state
  become: yes
  service:
    name: spss5
    state: "{{ new_state }}"
    
- name: change AMOR dimetix simulation state
  become: yes
  service:
    name: dimetix
    state: "{{ new_state }}"

- name: change AMOR IOC state
  become: yes
  service:
    name: amor_ioc
    state: "{{ new_state }}"

- name: change kafka server state
  become: yes
  service:
    name: kafka
    state: "{{ new_state }}"

- name: change generator simulation state
  become: yes
  service:
    name: generator
    state: "{{ new_state }}"

- name: change dornier chopper simulation state
  service:
    name: chopper_SIM_SINQ
    enabled: yes
    state: "{{ new_state }}"
  tags:
    - dornier
  become: yes

- name: change dornier chopper facade simulation state
  service:
    name: facade-chopper-dornier
    enabled: yes
    state: "{{ new_state }}"
  tags:
    - dornier
  become: yes
