// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PSISINQSCHEMA_H_
#define FLATBUFFERS_GENERATED_PSISINQSCHEMA_H_

#include "flatbuffers/flatbuffers.h"

struct EventData;

struct EventData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_HTYPE = 4,
    VT_PID = 6,
    VT_ST = 8,
    VT_TS = 10,
    VT_TR = 12,
    VT_DS = 14,
    VT_NEV = 16,
    VT_HWS = 18,
    VT_DATA = 20
  };
  const flatbuffers::String *htype() const { return GetPointer<const flatbuffers::String *>(VT_HTYPE); }
  uint32_t pid() const { return GetField<uint32_t>(VT_PID, 0); }
  uint32_t st() const { return GetField<uint32_t>(VT_ST, 0); }
  uint32_t ts() const { return GetField<uint32_t>(VT_TS, 0); }
  double tr() const { return GetField<double>(VT_TR, 0.0); }
  const flatbuffers::Vector<uint32_t> *ds() const { return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_DS); }
  uint32_t nev() const { return GetField<uint32_t>(VT_NEV, 0); }
  const flatbuffers::Vector<uint32_t> *hws() const { return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_HWS); }
  const flatbuffers::Vector<uint64_t> *data() const { return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_DATA); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_HTYPE) &&
           verifier.Verify(htype()) &&
           VerifyField<uint32_t>(verifier, VT_PID) &&
           VerifyField<uint32_t>(verifier, VT_ST) &&
           VerifyField<uint32_t>(verifier, VT_TS) &&
           VerifyField<double>(verifier, VT_TR) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_DS) &&
           verifier.Verify(ds()) &&
           VerifyField<uint32_t>(verifier, VT_NEV) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_HWS) &&
           verifier.Verify(hws()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_DATA) &&
           verifier.Verify(data()) &&
           verifier.EndTable();
  }
};

struct EventDataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_htype(flatbuffers::Offset<flatbuffers::String> htype) { fbb_.AddOffset(EventData::VT_HTYPE, htype); }
  void add_pid(uint32_t pid) { fbb_.AddElement<uint32_t>(EventData::VT_PID, pid, 0); }
  void add_st(uint32_t st) { fbb_.AddElement<uint32_t>(EventData::VT_ST, st, 0); }
  void add_ts(uint32_t ts) { fbb_.AddElement<uint32_t>(EventData::VT_TS, ts, 0); }
  void add_tr(double tr) { fbb_.AddElement<double>(EventData::VT_TR, tr, 0.0); }
  void add_ds(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> ds) { fbb_.AddOffset(EventData::VT_DS, ds); }
  void add_nev(uint32_t nev) { fbb_.AddElement<uint32_t>(EventData::VT_NEV, nev, 0); }
  void add_hws(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> hws) { fbb_.AddOffset(EventData::VT_HWS, hws); }
  void add_data(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> data) { fbb_.AddOffset(EventData::VT_DATA, data); }
  EventDataBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  EventDataBuilder &operator=(const EventDataBuilder &);
  flatbuffers::Offset<EventData> Finish() {
    auto o = flatbuffers::Offset<EventData>(fbb_.EndTable(start_, 9));
    return o;
  }
};

inline flatbuffers::Offset<EventData> CreateEventData(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<flatbuffers::String> htype = 0,
   uint32_t pid = 0,
   uint32_t st = 0,
   uint32_t ts = 0,
   double tr = 0.0,
   flatbuffers::Offset<flatbuffers::Vector<uint32_t>> ds = 0,
   uint32_t nev = 0,
   flatbuffers::Offset<flatbuffers::Vector<uint32_t>> hws = 0,
   flatbuffers::Offset<flatbuffers::Vector<uint64_t>> data = 0) {
  EventDataBuilder builder_(_fbb);
  builder_.add_tr(tr);
  builder_.add_data(data);
  builder_.add_hws(hws);
  builder_.add_nev(nev);
  builder_.add_ds(ds);
  builder_.add_ts(ts);
  builder_.add_st(st);
  builder_.add_pid(pid);
  builder_.add_htype(htype);
  return builder_.Finish();
}

inline const EventData *GetEventData(const void *buf) { return flatbuffers::GetRoot<EventData>(buf); }

inline bool VerifyEventDataBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<EventData>(); }

inline void FinishEventDataBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<EventData> root) { fbb.Finish(root); }


#endif  // FLATBUFFERS_GENERATED_PSISINQSCHEMA_H_
